import type { Langue } from "@/config/citystar";

/** Textes de l'espace propriétaire, dans les six langues du site. */
const fr = {
  connexion: {
    titre: "Connexion à mon espace",
    texte:
      "Saisissez l’adresse e-mail donnée lors de votre réservation. Vous recevrez un lien de connexion, sans mot de passe.",
    email: "Adresse e-mail",
    envoyer: "Recevoir mon lien",
    envoi: "Envoi en cours…",
    envoye: (email: string) =>
      `Un lien de connexion vient de partir vers ${email}. Ouvrez-le depuis cet appareil.`,
    autre: "Utiliser une autre adresse",
    pasAcces: "Pas encore d’accès ?",
    demander: "Demander mon accès",
    erreurEnvoi: "L’envoi a échoué. Vérifiez l’adresse, puis réessayez.",
    erreurLimite: "Trop de demandes en peu de temps. Réessayez dans quelques minutes.",
    erreurLien: "Ce lien a expiré ou a déjà servi. Demandez-en un nouveau ci-dessous.",
  },
  chargement: "Chargement de votre espace…",
  erreur: "Votre espace n’a pas pu être chargé.",
  reessayer: "Réessayer",
  connecte: (email: string) => `Connecté avec ${email}`,
  deconnexion: "Se déconnecter",
  promoteur: "Espace promoteur",
  aucun: {
    titre: "Aucune villa n’est encore reliée à cette adresse.",
    texte:
      "Votre conseiller relie votre villa à votre adresse e-mail après la réservation. Si c’est déjà fait, écrivez-nous.",
  },
  villa: (numero: number) => `Villa ${String(numero).padStart(2, "0")}`,
  type: (type: string) => `Type ${type}`,
  choisir: "Mes villas",
  avancement: "Avancement des travaux",
  majLe: (date: string) => `Mis à jour le ${date}`,
  mot: "Le mot du promoteur",
  etapes: {
    titre: "Les étapes du chantier",
    statuts: { a_venir: "À venir", en_cours: "En cours", termine: "Terminée" },
    prevue: (date: string) => `Prévue le ${date}`,
    finie: (date: string) => `Terminée le ${date}`,
  },
  paiements: {
    titre: "Mes paiements",
    regle: "Réglé",
    reste: "Reste à régler",
    total: "Prix de la villa",
    paye: (date: string) => `Réglé le ${date}`,
    echeance: (date: string) => `Échéance le ${date}`,
    sansDate: "Date à venir",
    aRegler: "À régler",
    aVenir: "À venir",
    vide: "L’échéancier de votre villa apparaîtra ici.",
  },
  photos: {
    titre: "Photos du chantier",
    domaine: "Domaine",
    vide: "Les premières photos du chantier arriveront ici.",
    agrandir: "Agrandir la photo",
    fermer: "Fermer",
    precedente: "Photo précédente",
    suivante: "Photo suivante",
  },
  documents: {
    titre: "Mes documents",
    vide: "Vos contrats, plans et appels de fonds seront rangés ici.",
    ouvrir: "Télécharger",
    categories: {
      contrat: "Contrat",
      plan: "Plan",
      appel: "Appel de fonds",
      recu: "Reçu",
      autre: "Document",
    },
  },
};

export type TextesEspace = typeof fr;

const en: TextesEspace = {
  connexion: {
    titre: "Sign in to my owner area",
    texte:
      "Enter the email address you gave when reserving. You will receive a sign-in link, no password needed.",
    email: "Email address",
    envoyer: "Send my link",
    envoi: "Sending…",
    envoye: (email) => `A sign-in link is on its way to ${email}. Open it on this device.`,
    autre: "Use another address",
    pasAcces: "No access yet?",
    demander: "Request my access",
    erreurEnvoi: "Sending failed. Check the address, then try again.",
    erreurLimite: "Too many requests in a short time. Try again in a few minutes.",
    erreurLien: "This link has expired or was already used. Request a new one below.",
  },
  chargement: "Loading your owner area…",
  erreur: "Your owner area could not be loaded.",
  reessayer: "Try again",
  connecte: (email) => `Signed in as ${email}`,
  deconnexion: "Sign out",
  promoteur: "Developer area",
  aucun: {
    titre: "No villa is linked to this address yet.",
    texte:
      "Your adviser links your villa to your email address after the reservation. If that is already done, write to us.",
  },
  villa: (numero) => `Villa ${String(numero).padStart(2, "0")}`,
  type: (type) => `Type ${type}`,
  choisir: "My villas",
  avancement: "Construction progress",
  majLe: (date) => `Updated ${date}`,
  mot: "A word from the developer",
  etapes: {
    titre: "Construction stages",
    statuts: { a_venir: "Upcoming", en_cours: "In progress", termine: "Completed" },
    prevue: (date) => `Planned for ${date}`,
    finie: (date) => `Completed on ${date}`,
  },
  paiements: {
    titre: "My payments",
    regle: "Paid",
    reste: "Left to pay",
    total: "Villa price",
    paye: (date) => `Paid on ${date}`,
    echeance: (date) => `Due ${date}`,
    sansDate: "Date to come",
    aRegler: "Due",
    aVenir: "Upcoming",
    vide: "Your villa’s payment schedule will appear here.",
  },
  photos: {
    titre: "Construction photos",
    domaine: "Estate",
    vide: "The first construction photos will appear here.",
    agrandir: "Enlarge photo",
    fermer: "Close",
    precedente: "Previous photo",
    suivante: "Next photo",
  },
  documents: {
    titre: "My documents",
    vide: "Your contracts, plans and payment calls will be filed here.",
    ouvrir: "Download",
    categories: {
      contrat: "Contract",
      plan: "Plan",
      appel: "Payment call",
      recu: "Receipt",
      autre: "Document",
    },
  },
};

const es: TextesEspace = {
  connexion: {
    titre: "Acceso a mi espacio",
    texte:
      "Introduzca el correo electrónico que indicó al reservar. Recibirá un enlace de acceso, sin contraseña.",
    email: "Correo electrónico",
    envoyer: "Recibir mi enlace",
    envoi: "Enviando…",
    envoye: (email) => `Le hemos enviado un enlace de acceso a ${email}. Ábralo en este dispositivo.`,
    autre: "Usar otra dirección",
    pasAcces: "¿Aún no tiene acceso?",
    demander: "Solicitar mi acceso",
    erreurEnvoi: "No se pudo enviar. Compruebe la dirección y vuelva a intentarlo.",
    erreurLimite: "Demasiadas solicitudes seguidas. Inténtelo de nuevo en unos minutos.",
    erreurLien: "Este enlace ha caducado o ya se ha usado. Solicite uno nuevo a continuación.",
  },
  chargement: "Cargando su espacio…",
  erreur: "No se ha podido cargar su espacio.",
  reessayer: "Reintentar",
  connecte: (email) => `Conectado como ${email}`,
  deconnexion: "Cerrar sesión",
  promoteur: "Espacio del promotor",
  aucun: {
    titre: "Todavía no hay ninguna villa vinculada a esta dirección.",
    texte:
      "Su asesor vincula su villa a su correo electrónico tras la reserva. Si ya está hecho, escríbanos.",
  },
  villa: (numero) => `Villa ${String(numero).padStart(2, "0")}`,
  type: (type) => `Tipo ${type}`,
  choisir: "Mis villas",
  avancement: "Avance de las obras",
  majLe: (date) => `Actualizado el ${date}`,
  mot: "Unas palabras del promotor",
  etapes: {
    titre: "Las etapas de la obra",
    statuts: { a_venir: "Próxima", en_cours: "En curso", termine: "Terminada" },
    prevue: (date) => `Prevista el ${date}`,
    finie: (date) => `Terminada el ${date}`,
  },
  paiements: {
    titre: "Mis pagos",
    regle: "Pagado",
    reste: "Pendiente",
    total: "Precio de la villa",
    paye: (date) => `Pagado el ${date}`,
    echeance: (date) => `Vencimiento el ${date}`,
    sansDate: "Fecha por fijar",
    aRegler: "A pagar",
    aVenir: "Próximo",
    vide: "El calendario de pagos de su villa aparecerá aquí.",
  },
  photos: {
    titre: "Fotos de la obra",
    domaine: "Conjunto",
    vide: "Las primeras fotos de la obra aparecerán aquí.",
    agrandir: "Ampliar la foto",
    fermer: "Cerrar",
    precedente: "Foto anterior",
    suivante: "Foto siguiente",
  },
  documents: {
    titre: "Mis documentos",
    vide: "Sus contratos, planos y solicitudes de pago se guardarán aquí.",
    ouvrir: "Descargar",
    categories: {
      contrat: "Contrato",
      plan: "Plano",
      appel: "Solicitud de pago",
      recu: "Recibo",
      autre: "Documento",
    },
  },
};

const it: TextesEspace = {
  connexion: {
    titre: "Accesso alla mia area",
    texte:
      "Inserisca l’indirizzo e-mail indicato al momento della prenotazione. Riceverà un link di accesso, senza password.",
    email: "Indirizzo e-mail",
    envoyer: "Ricevi il mio link",
    envoi: "Invio in corso…",
    envoye: (email) => `Un link di accesso è stato inviato a ${email}. Lo apra da questo dispositivo.`,
    autre: "Usa un altro indirizzo",
    pasAcces: "Non ha ancora un accesso?",
    demander: "Richiedi il mio accesso",
    erreurEnvoi: "Invio non riuscito. Controlli l’indirizzo e riprovi.",
    erreurLimite: "Troppe richieste in poco tempo. Riprovi tra qualche minuto.",
    erreurLien: "Questo link è scaduto o è già stato usato. Ne richieda uno nuovo qui sotto.",
  },
  chargement: "Caricamento della sua area…",
  erreur: "Non è stato possibile caricare la sua area.",
  reessayer: "Riprova",
  connecte: (email) => `Connesso come ${email}`,
  deconnexion: "Esci",
  promoteur: "Area del promotore",
  aucun: {
    titre: "Nessuna villa è ancora collegata a questo indirizzo.",
    texte:
      "Il suo consulente collega la villa al suo indirizzo e-mail dopo la prenotazione. Se è già stato fatto, ci scriva.",
  },
  villa: (numero) => `Villa ${String(numero).padStart(2, "0")}`,
  type: (type) => `Tipo ${type}`,
  choisir: "Le mie ville",
  avancement: "Avanzamento dei lavori",
  majLe: (date) => `Aggiornato il ${date}`,
  mot: "Una parola dal promotore",
  etapes: {
    titre: "Le fasi del cantiere",
    statuts: { a_venir: "Da avviare", en_cours: "In corso", termine: "Completata" },
    prevue: (date) => `Prevista il ${date}`,
    finie: (date) => `Completata il ${date}`,
  },
  paiements: {
    titre: "I miei pagamenti",
    regle: "Pagato",
    reste: "Da pagare",
    total: "Prezzo della villa",
    paye: (date) => `Pagato il ${date}`,
    echeance: (date) => `Scadenza il ${date}`,
    sansDate: "Data da definire",
    aRegler: "Da pagare",
    aVenir: "In arrivo",
    vide: "Il piano dei pagamenti della sua villa apparirà qui.",
  },
  photos: {
    titre: "Foto del cantiere",
    domaine: "Complesso",
    vide: "Le prime foto del cantiere arriveranno qui.",
    agrandir: "Ingrandisci la foto",
    fermer: "Chiudi",
    precedente: "Foto precedente",
    suivante: "Foto successiva",
  },
  documents: {
    titre: "I miei documenti",
    vide: "Contratti, planimetrie e richieste di pagamento saranno archiviati qui.",
    ouvrir: "Scarica",
    categories: {
      contrat: "Contratto",
      plan: "Planimetria",
      appel: "Richiesta di pagamento",
      recu: "Ricevuta",
      autre: "Documento",
    },
  },
};

const nl: TextesEspace = {
  connexion: {
    titre: "Inloggen op mijn omgeving",
    texte:
      "Vul het e-mailadres in dat u bij de reservering opgaf. U ontvangt een inloglink, zonder wachtwoord.",
    email: "E-mailadres",
    envoyer: "Stuur mijn link",
    envoi: "Bezig met verzenden…",
    envoye: (email) => `Er is een inloglink verstuurd naar ${email}. Open hem op dit apparaat.`,
    autre: "Een ander adres gebruiken",
    pasAcces: "Nog geen toegang?",
    demander: "Toegang aanvragen",
    erreurEnvoi: "Verzenden is mislukt. Controleer het adres en probeer het opnieuw.",
    erreurLimite: "Te veel aanvragen in korte tijd. Probeer het over enkele minuten opnieuw.",
    erreurLien: "Deze link is verlopen of al gebruikt. Vraag hieronder een nieuwe aan.",
  },
  chargement: "Uw omgeving wordt geladen…",
  erreur: "Uw omgeving kon niet worden geladen.",
  reessayer: "Opnieuw proberen",
  connecte: (email) => `Ingelogd als ${email}`,
  deconnexion: "Uitloggen",
  promoteur: "Omgeving projectontwikkelaar",
  aucun: {
    titre: "Er is nog geen villa aan dit adres gekoppeld.",
    texte:
      "Uw adviseur koppelt uw villa na de reservering aan uw e-mailadres. Is dat al gebeurd, schrijf ons dan.",
  },
  villa: (numero) => `Villa ${String(numero).padStart(2, "0")}`,
  type: (type) => `Type ${type}`,
  choisir: "Mijn villa’s",
  avancement: "Voortgang van de bouw",
  majLe: (date) => `Bijgewerkt op ${date}`,
  mot: "Een woord van de ontwikkelaar",
  etapes: {
    titre: "De fasen van de bouw",
    statuts: { a_venir: "Gepland", en_cours: "Bezig", termine: "Afgerond" },
    prevue: (date) => `Gepland op ${date}`,
    finie: (date) => `Afgerond op ${date}`,
  },
  paiements: {
    titre: "Mijn betalingen",
    regle: "Betaald",
    reste: "Nog te betalen",
    total: "Prijs van de villa",
    paye: (date) => `Betaald op ${date}`,
    echeance: (date) => `Vervalt op ${date}`,
    sansDate: "Datum volgt",
    aRegler: "Te betalen",
    aVenir: "Gepland",
    vide: "Het betalingsschema van uw villa verschijnt hier.",
  },
  photos: {
    titre: "Bouwfoto’s",
    domaine: "Domein",
    vide: "De eerste bouwfoto’s verschijnen hier.",
    agrandir: "Foto vergroten",
    fermer: "Sluiten",
    precedente: "Vorige foto",
    suivante: "Volgende foto",
  },
  documents: {
    titre: "Mijn documenten",
    vide: "Uw contracten, plannen en betalingsverzoeken worden hier bewaard.",
    ouvrir: "Downloaden",
    categories: {
      contrat: "Contract",
      plan: "Plattegrond",
      appel: "Betalingsverzoek",
      recu: "Kwitantie",
      autre: "Document",
    },
  },
};

const no: TextesEspace = {
  connexion: {
    titre: "Logg inn på eiersiden",
    texte:
      "Skriv inn e-postadressen du oppga ved reservasjonen. Du får en innloggingslenke, uten passord.",
    email: "E-postadresse",
    envoyer: "Send meg lenken",
    envoi: "Sender…",
    envoye: (email) => `En innloggingslenke er sendt til ${email}. Åpne den på denne enheten.`,
    autre: "Bruk en annen adresse",
    pasAcces: "Har du ikke tilgang ennå?",
    demander: "Be om tilgang",
    erreurEnvoi: "Sendingen mislyktes. Sjekk adressen og prøv igjen.",
    erreurLimite: "For mange forespørsler på kort tid. Prøv igjen om noen minutter.",
    erreurLien: "Denne lenken er utløpt eller allerede brukt. Be om en ny nedenfor.",
  },
  chargement: "Laster eiersiden…",
  erreur: "Eiersiden kunne ikke lastes.",
  reessayer: "Prøv igjen",
  connecte: (email) => `Logget inn som ${email}`,
  deconnexion: "Logg ut",
  promoteur: "Utbyggersiden",
  aucun: {
    titre: "Ingen villa er knyttet til denne adressen ennå.",
    texte:
      "Rådgiveren din knytter villaen til e-postadressen din etter reservasjonen. Er det allerede gjort, skriv til oss.",
  },
  villa: (numero) => `Villa ${String(numero).padStart(2, "0")}`,
  type: (type) => `Type ${type}`,
  choisir: "Mine villaer",
  avancement: "Fremdrift i byggingen",
  majLe: (date) => `Oppdatert ${date}`,
  mot: "Et ord fra utbyggeren",
  etapes: {
    titre: "Etappene i byggingen",
    statuts: { a_venir: "Kommer", en_cours: "Pågår", termine: "Ferdig" },
    prevue: (date) => `Planlagt ${date}`,
    finie: (date) => `Ferdig ${date}`,
  },
  paiements: {
    titre: "Mine betalinger",
    regle: "Betalt",
    reste: "Gjenstår",
    total: "Pris på villaen",
    paye: (date) => `Betalt ${date}`,
    echeance: (date) => `Forfaller ${date}`,
    sansDate: "Dato kommer",
    aRegler: "Til betaling",
    aVenir: "Kommer",
    vide: "Betalingsplanen for villaen din vises her.",
  },
  photos: {
    titre: "Bilder fra byggeplassen",
    domaine: "Området",
    vide: "De første bildene fra byggeplassen kommer her.",
    agrandir: "Forstørr bildet",
    fermer: "Lukk",
    precedente: "Forrige bilde",
    suivante: "Neste bilde",
  },
  documents: {
    titre: "Mine dokumenter",
    vide: "Kontrakter, tegninger og betalingsvarsler blir lagt her.",
    ouvrir: "Last ned",
    categories: {
      contrat: "Kontrakt",
      plan: "Tegning",
      appel: "Betalingsvarsel",
      recu: "Kvittering",
      autre: "Dokument",
    },
  },
};

export const textesEspace: Record<Langue, TextesEspace> = { fr, en, es, it, nl, no };
